<a href="https://colab.research.google.com/github/tshs10831182/tshs10831182repo/blob/master/Week_8_Python%E7%9A%84%E9%9A%A8%E6%A9%9F%E6%95%B8%E8%88%87%E6%97%A5%E6%9C%9F%E6%99%82%E9%96%93%E8%99%95%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](http://www.tshs.tp.edu.tw/images/bg/logo.jpg) 

## 多元選修課程：Python與人工智慧程式設計

# 【第八週】Python的隨機數與日期時間處理

在資料分析與AI程式設計的領域中常會需要運用隨機(random)數的方法來處理資料及模型，例如在深度學習的模型訓練時，常用隨機值來初始化訓練權重。

要了解Python提供的隨機數功能，今天的內容分為Python內建的 `random` 模組，以及 NumPy 提供的 `random` 模組來介紹。

### 【任務8-1】模擬擲骰子：認識Python `random` 模組

在使用 `random` 模組前，須先 import。

In [ ]:
import random

隨機數產生的種子(seed)，程式會根據種子產生隨機數。如果沒有指定種子的話，會使用**系統時間**來當做種子。

【註】在這邊我們指定種子的主要原因為了要讓每次產生的隨機數都相同，在學習或是除錯時比較方便。

In [ ]:
random.seed(3)

從固定區間的數字中產生隨機**整數**，可以使用下列函式及語法：

```python
random.randint(a, b)
```

其中，產生隨機整數$N$的值為介於$a$和$b$之間($a \le N \le b$)

下面的範例，模擬擲骰子10000次，將每次擲出來的數字使用串列的 `append()` 函式存到串列中。

In [ ]:
a = []

for i in range(10000):
    a.append(random.randint(1, 6))

In [ ]:
# 列出前10筆查看
a[0:10]

[2, 5, 5, 2, 3, 5, 4, 6, 5, 1]

使用串列的 `count()` 函式，可以統計串列中每個元素出現的次數，我們可以用來統計骰子擲出數字的次數。

語法：

```python
串列名稱.count(元素值)
```

In [ ]:
for j in range(1, 7):
    print(j, "出現的次數：", a.count(j))

1 出現的次數： 1658
2 出現的次數： 1653
3 出現的次數： 1769
4 出現的次數： 1695
5 出現的次數： 1645
6 出現的次數： 1580


另一個寫法，我們從 [1, 2, 3, 4, 5, 6] 串列中，隨機抽取一個元素，模擬擲骰子。

語法：

```python
random.choice(串列)
```

我們將抽取出來的數字存到另一個串列，最後用串列的 `count()` 與 `len()` 函式相除，計算抽到3的機率是多少。理論上，擲骰子擲出每個數字的機率應該都是約 16.67%。

In [ ]:
a = []
dice = [1, 2, 3, 4, 5, 6]

for i in range(10000):
    a.append(random.choice(dice))

a.count(3) / len(a)

0.1728

### 【回憶】曾經體驗過的 `shuffle()`

在上次的課程中，我們曾經體驗過將串列中的元素洗牌。

```python
random.shuffle(five_words)
```

shuffle 接受傳入的引數是串列名稱。下面的例子是將1~10數字串列洗牌。

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

random.shuffle(a)
a

[4, 3, 6, 2, 10, 7, 9, 8, 5, 1]

### 【任務8-2】如何隨機產生浮點數

相較於 `randint()` 產生的隨機數是整數，`random()` 和 `uniform()` 函式產生的則是浮點數。兩個函式主要的差異在於 `random()` 產生的隨機數是介於 0 和 1.0 (不包含1.0)；`uniform()` 產生的隨機數$N$的值為介於起始值$a$和結束值$b$之間($a \le N \le b$)。

語法：

```python
random.random()
random.uniform(a, b)
```

In [ ]:
random.random()

0.9632231371526404

In [ ]:
random.uniform(1, 10)

8.520739743647205

### 【任務8-3】從一堆數字裡面，隨機取出指定數目的數字

如果要從一堆數字裡面，隨機取出指定數目的數字，可以使用 `sample()` 函式。

In [ ]:
b = [1.0, 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8, 10.1]
random.sample(b, 6)

[2.1, 10.1, 3.2, 8.7, 1.0, 5.4]

### 【任務8-4】初識 NumPy 的 `random` 模組

NumPy 提供提供非常多隨機數函式，下面介紹幾個常用的函式，可以用來產生元素為隨機數的多維陣列。

|函式|說明|產生數值區間|隨機數資料型別|隨機數分佈|
|---|---|---|---|---|
|rand()|隨機產生指定形狀(shape)的陣列|[0, 1)|浮點數|連續型均勻分布|
|randn()|隨機產生指定形狀(shape)的陣列|(-1, 1)|浮點數|常態分佈|
|randint((low[, high, size, dtype]))|隨機產生設定區間元素|[low, high)|整數|離散型均勻分布|
|random([size])|隨機產生指定大小的一維陣列|[0.0, 1.0)|浮點數|連續型均勻分布|

In [ ]:
import numpy as np

隨機產生10個隨機整數的一維陣列，數字介於1到9之間。

In [ ]:
np.random.randint(1, 10, 10)

array([9, 4, 3, 6, 8, 1, 1, 1, 7, 4])

隨機產生10個隨機浮點數的一維陣列，數字介於0到1.0之間(不包含1.0)。

In [ ]:
np.random.random(10)

array([0.20531414, 0.79451221, 0.35639023, 0.30032098, 0.0386285 ,
       0.96161737, 0.39767788, 0.60789872, 0.45908778, 0.07559442])

類似Python random模組的 `choice()` 函式，NumPy也提供 `choice()` 函式。下面的範例產生1到6之間的10個整數陣列。

In [ ]:
np.random.choice(range(1, 7), 10)

array([3, 4, 3, 5, 1, 3, 5, 3, 1, 2])

隨機產生指定形狀的陣列，`numpy.random.rand()` 與 `numpy.random.randn()` 不同之處在於產生數值區間和隨機數分佈。

|函式|說明|產生數值區間|隨機數資料型別|隨機數分佈|
|---|---|---|---|---|
|rand()|隨機產生指定形狀(shape)的陣列|[0, 1)|浮點數|連續型均勻分布|
|randn()|隨機產生指定形狀(shape)的陣列|(-1, 1)|浮點數|常態分佈|

下面的例子是隨機產生 2 $\times$ 3 形狀的二維陣列。

In [ ]:
np.random.rand(2, 3)

array([[0.16147789, 0.06035064, 0.8264096 ],
       [0.4498146 , 0.59004676, 0.79127071]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.55616966, -1.03495053, -2.20619412],
       [ 1.42066686, -1.59606025,  1.08476654]])

### 【挑戰】家人想買大樂透但是不知道該買什麼號碼，做一個隨機選號產生器吧

![](https://www.taiwanlottery.com.tw/images/loto_image01.jpg)

圖片來源：台灣彩券

大樂透的投注方式是從01~49中任選6個號碼進行投注。

提示：
1. 在隨機選號前，提示使用者輸入一個幸運號碼。
2. 隨機從1~49中選出要簽注的號碼。
3. 確定每次隨機選出的號碼，沒有跟幸運號碼或是已選出的號碼重覆。

In [ ]:
luckynum = input("請輸入一個幸運號碼：")

In [ ]:
lottery = []
excludenum = []

# 請從下一行開始撰寫程式


### 【挑戰】利用蒙地卡羅方法，估算圓周率

圓周率 $\pi$ 是一個無理數，它的小數部分是無限不循環小數，其數字序列被認為是隨機分布的。自古以來數學家們嘗試用不同的方法來計算較精確的 $\pi$。

蒙地卡羅方法 (Monte Carlo Method) 也稱為統計類比方法，可透過隨機分布的特徵數轉化為求解問題的答案，例如隨機數出現的機率。利用蒙地卡羅方法，估算圓周率的方式是藉由輸入隨機數來計算圓面積的過程，計算出圓周率 $\pi$。

![](https://drive.google.com/uc?export=view&id=1Coe9Wy4akrXPXnBjbd4XKir41Q8MD_2G)

假設有一個直徑長為 1 的圓形，要使用蒙地卡羅方法計算其面積，我們隨機塞入 N 個點到上面的正方形當中，有些點會落在圓形內而有些點會在圓形外，算出落在圓形內點的數目就可以得到圓形的面積。

假設半徑 $r=0.5$，圓形面積的計算公式為

$$\pi r^2=\pi\times0.5^2=\frac{\pi}{4}$$

並以此得到 $$\pi=4\times面積=4\times\frac{落在圓內的點}{所有的點}$$

提示：
- 隨機產生x, y的值做為隨機點的座標。x, y值介於0到1之間。
- 判斷隨機點的座標到圓心的距離如果小於半徑的話，表示這個點在圓內。

In [ ]:
# 半徑長度
radius = 0.5

In [ ]:
# 設定隨機數產生的數目
n = 10000

In [ ]:
# 請從下一行開始撰寫程式


**可以嘗試改變程式中的 N 值 (例如更新為 300000)，觀察看看 mypi 的值是否有所不同。**

### 日期與時間

日期與時間在資料分析時是常常會遇到的資料內容，但是由於各個國家、語系、時區... 對於日期與時間的撰寫和表達方式各有不同，所以有好的工具來處理日期與時間是很重要的。Python提供 `datetime`、`date`、`time`、`timedelta`、`calendar` 等模組或類別來輔助日期與時間的處理工作。

今天的課程中將介紹 `datetime`、`timedelta`、`calendar` 等模組及常用的功能。

### 【任務8-5】產生年曆和月曆只要一行程式 - `calendar` 模組

匯入模組

In [ ]:
import calendar

`calendar` 預設的"週"啟始日是週一，從索引0開始。以台灣的習慣來說，我們將每週的第一天設為6，也就是週日。

In [ ]:
calendar.setfirstweekday(6)

印出年曆只要一行程式！兩種方式：

calendar() 函式回傳的是字串，在輸出時會包含跳脫字元，若使用 `print()` 輸出就可以顯示完整的格式，語法如下：

```python
calendar.calendar(西元年份)
```

`prcal()` 函式則是會直接輸出排列整齊的格式。語法如下：

```python
calendar.prcal(西元年份)
```

In [ ]:
# 年曆的原始字串
calendar.calendar(2021)

'                                  2021\n\n      January                   February                   March\nSu Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa\n                1  2          1  2  3  4  5  6          1  2  3  4  5  6\n 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13\n10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20\n17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27\n24 25 26 27 28 29 30      28                        28 29 30 31\n31\n\n       April                      May                       June\nSu Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa\n             1  2  3                         1             1  2  3  4  5\n 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12\n11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19\n18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26\n25 26 27 28 29

In [ ]:
# 印出2021年曆
print(calendar.calendar(2021))

                                  2021

      January                   February                   March
Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 

印出月曆只要一行程式！語法如下：

```python
calendar.prmonth(西元年份, 月份)
```

In [ ]:
print(calendar.month(2020, 10))

    October 2020
Su Mo Tu We Th Fr Sa
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



判斷某一年是否為閏年，呼叫 `isleap()` 函式，傳入西元年份即可。

In [ ]:
calendar.isleap(2021)

False

想要知道某一個月份的第一天是星期幾、該月總共有幾天，可以透過 `monthrange()` 函式。

下面範例示範2020年10月1日是週四，該月有31天。

In [ ]:
calendar.monthrange(2020, 10)

(3, 31)

### 【任務8-6】認識最主要的日期時間模組 - `datetime`

載入模組和函式。

In [ ]:
from datetime import datetime

建立日期時間物件的方式，傳入西元年月日，時間未傳入的話預設值都為0。

In [ ]:
datetime(2020, 10, 21)

datetime.datetime(2020, 10, 21, 0, 0)

建立時也可以傳入時間。

In [ ]:
datetime(2020, 10, 21, 12, 0, 0)

datetime.datetime(2020, 10, 21, 12, 0)

In [ ]:
datetime.now()

datetime.datetime(2020, 10, 22, 12, 7, 35, 45771)

日期時間物件之間可以進行減法，算出兩個日期時間之間的差距。

現在的日期時間都可以用 `now()` 函式取得。

In [ ]:
a = datetime.now()
b = datetime(2020, 10, 10)

a - b

datetime.timedelta(days=12, seconds=43655, microseconds=726435)

從日期時間物件的屬性，分別取得年、月、日、時、分、秒。`weekday()` 函式則是取得星期幾。

In [ ]:
print(datetime.now().year)
print(datetime.now().month)
print(datetime.now().day)
print(datetime.now().hour)
print(datetime.now().minute)
print(datetime.now().second)
print(datetime.now().weekday())

2020
10
22
12
7
36
3


### 【任務8-7】字串與日期時間互相轉換

因為每個人寫日期時間格式可能各有不同，字串與日期時間之間轉換時，需要告訴程式格式，才能正確地解析。常用的日期時間格式碼如下，完整的格式碼可以參考 [strftime() and strptime() Format Codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)。

|格式碼|意義|範例|
|---|---|---|
|%Y|完整西元年|2000, 2010, 2020|
|%y|簡寫西元年|01, 02, 20|
|%m|月份|01, 02, …, 12|
|%d|日|01, 02, …, 31|
|%H|時|00, 01, …, 23|
|%M|分|00, 01, …, 59|
|%S|秒|00, 01, …, 59|

利用Python提供的函式來進行轉換：
- `strptime()`：將字串轉為 datetime
- `strftime()`：將 datetime 轉為字串

`strptime()` 語法：

```python
datetime.strptime(包含日期時間的字串, 日期時間的格式)
```

In [ ]:
str = "2020-10-21"
dt = datetime.strptime(str, '%Y-%m-%d')
dt

datetime.datetime(2020, 10, 21, 0, 0)

`strftime()` 語法：

```python
datetime.strftime(要轉出字串的格式)
```

In [ ]:
dt.strftime('%y年%m月%d日')

'20年10月21日'

### 【任務8-8】用 `timedelta` 來做日期時間運算

`timedelta` 物件是**一段**日期時間間隔，可以用來跟 `datetime` 進行加減法運算。

timedelta語法：

```python
timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)
```

例如：世界協調時間(UTC)時區比台北時區(Asia/Taipei)晚8小時，所以UTC時區現在時間可以用範例程式碼算出。

In [ ]:
from datetime import timedelta

delta = timedelta(hours=8)

UTCnow = datetime.now() - delta
UTCnow

datetime.datetime(2020, 10, 22, 4, 7, 40, 6856)

日期時間的物件之間不能相加，但是跟 `timedelta` 就可以相加。例如2021年大學指考的倒數100天是從3/23起算，加100天就是指考。

範例中使用另一個建立 `datetime` 物件的方式 - `fromisoformat()` 函式，ISO格式的日期時間是 `YYYY-MM-DD[*HH[:MM[:SS]]]`，傳入正確格式字串就可以建立。

In [ ]:
datetime.fromisoformat('2021-03-23 08:00:00') + timedelta(days=100)

datetime.datetime(2021, 7, 1, 8, 0)

### 【挑戰】從現在到你的大學指考還有多少天？

請用Python `datetime` 算出輸入的大學指考第一天日期，從今天算起還有多少天？

In [ ]:
userinput = input("輸入大學指考日期(格式: 西元年/月/日)")

In [ ]:
# 請從下一行開始撰寫程式
